name: FD5to6Finance
options:
  bundleIdPrefix: com.jw
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16"
  createIntermediateGroups: true

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 7.1.0

targets:
  FD5to6Finance:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Finance
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        GIDClientID: 71319598693-k61ifvsdv9nojn5fq61hfilnsadgpsq1.apps.googleusercontent.com
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - com.googleusercontent.apps.71319598693-k61ifvsdv9nojn5fq61hfilnsadgpsq1
    dependencies:
      - package: GoogleSignIn
    settings:
      base:
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.junwon.fd5to6finance
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: 3N9UDPW4BP
